/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
    docsSidebar: [
        { type: 'doc', id: 'index', label: 'About Coilpack' },
        'getting-started',
        {
            type: 'category',
            label: 'Guides',
            collapsed: false,
            collapsible: false,
            items: ['guides/twig'],
        },
        'configuration',
        'events',
        'routing',
        {
            type: 'category',
            label: 'GraphQL',
            link: { type: 'doc', id: 'graphql/index' },
            items: [{
                type: 'category',
                label: 'Queries',
                items: [
                    'graphql/queries/categories',
                    'graphql/queries/channel-entries',
                    'graphql/queries/global-variables',
                    'graphql/queries/member-current',
                ],
            }],
        },
        'templates',
        {
            type: 'category',
            label: 'Tags',
            link: { type: 'doc', id: 'tags/index' },
            items: [
                'tags/channel-entries',
                'tags/email-contact',
                'tags/structure-entries',
            ],
        },
        {
            type: 'category',
            label: 'Advanced',
            items: [
                'advanced/addons',
                'advanced/authentication',
                'advanced/database',
                'advanced/filesystem',
            ],
        },
    ],
};

module.exports = sidebars;